= Building a Spring Boot Application

== Create a Spring Boot Project

. Browse to https://start.spring.io

. Generate a Maven Project with Spring Boot 1.3 (if this version is unavailable then get the latest 1.3.X version, but no SNAPSHOTS).

. Fill out the *Project metadata* fields as follows:
+
Group:: +io.pivotal+
Artifact:: +data-jpa-spring-boot+
Name:: data-spring-boot

. In the dependencies section, add the following:
+
*Web*, *Thymeleaf*, *JPA*,*H2*

. Click the _Generate Project_ button. Your browser will download a zip file. 

. Copy then unpack the downloaded zip file to *CN-Workshop-TM/labs/lab02/data-jpa-spring-boot*
+
Your directory structure should now look like:
+
[source, bash]
---------------------------------------------------------------------
CN-Workshop-TM:
├── labs
│   ├── lab02
│   │   ├── data-jpa-spring-boot
---------------------------------------------------------------------

. Import the project’s pom.xml into your editor/IDE of choice.
+
*_STS Import Help:_*
+
Select File > Import… Then select Maven > Existing Maven Projects. On the Import Maven Projects page, browse to the /data-jpa-spring-boot directory (e.g. CN-Workshop-TM/labs/lab02/data-jpa-spring-boot)

This application will create a simple reading list by asking for books you have read and storing them in a simple relational repository. The first stereotype we will need is the domain model itself, which is Book.

== Add the domain object - Book
. Add a Book object to the io.pivotal package with the required JPA annotations.
+
[source, java, numbered]
---------------------------------------------------------------------
package io.pivotal;

package io.pivotal;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Book {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;
	private String reader;
	private String isbn;
	private String title;
	private String author;
	private String description;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getReader() {
		return reader;
	}

	public void setReader(String reader) {
		this.reader = reader;
	}

	public String getIsbn() {
		return isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}

== Add an Repository in a separate Repository class that we'll name ReadingListRepository

. We extend a JpaRepository with our domain type and key type as parameters in  class _io.pivotal.ReadingListRepository_ (/data-jpa-spring-boot/src/main/java/io/pivotal/ReadingListRepository.java).
+
[source, java, numbered]
---------------------------------------------------------------------
 class _io.pivotal.ReadingListRepository_ (/data-jpa-spring-boot/src/main/java/io/pivotal/ReadingListRepository.java).
+
[source, java, numbered]
---------------------------------------------------------------------

== Add an Endpoint in a separate Controller class that we'll name ReadingListController

. Add an @RestController annotation to the class _io.pivotal.ReadingListController_ (/data-jpa-spring-boot/src/main/java/io/pivotal/ReadingListController.java).
+
[source, java, numbered]
---------------------------------------------------------------------
package io.pivotal;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
@RequestMapping("/readingList")
public class ReadingListController {

  private static final String reader = "craig";

	private ReadingListRepository readingListRepository;

	@Autowired
	public ReadingListController(ReadingListRepository readingListRepository) {
		this.readingListRepository = readingListRepository;
	}

	@RequestMapping(method=RequestMethod.GET)
	public String readersBooks(Model model) {

		List<Book> readingList = readingListRepository.findByReader(reader);
		if (readingList != null) {
			model.addAttribute("books", readingList);
		}
		return "readingList";
	}


}


---------------------------------------------------------------------

. Add the following request handler to the class _io.pivotal.HelloSpringBootApplication_ (/hello-spring-boot/src/main/java/io/pivotal/HelloSpringBootApplication.java).
+
[source,java]
---------------------------------------------------------------------
	@RequestMapping(method=RequestMethod.POST)
	public String addToReadingList(Book book) {
		book.setReader(reader);
		readingListRepository.save(book);
		return "redirect:/readingList";
	}

---------------------------------------------------------------------
. Add a web page so that we can see the book titles provided in an html thymeleaf page called _readingList.html_ (/hello-spring-boot/src/main/resources/templates/readingList.html).
+
[source,html]
<html>
  <head>
    <title>Reading List</title>
    <link rel="stylesheet" th:href="@{/style.css}"></link>
  </head>

  <body>
    <h2>Your Reading List</h2>
    <div th:unless="${#lists.isEmpty(books)}">
      <dl th:each="book : ${books}">
        <dt class="bookHeadline">
          <span th:text="${book.title}">Title</span> by
          <span th:text="${book.author}">Author</span>
          (ISBN: <span th:text="${book.isbn}">ISBN</span>)
        </dt>
        <dd class="bookDescription">
          <span th:if="${book.description}"
                th:text="${book.description}">Description</span>
          <span th:if="${book.description eq null}">
                No description available</span>
        </dd>
      </dl>
    </div>
    <div th:if="${#lists.isEmpty(books)}">
      <p>You have no books in your book list</p>
    </div>


    <hr/>

    <h3>Add a book</h3>
    <form method="POST">
      <label for="title">Title:</label>
        <input type="text" name="title" size="50"></input><br/>
      <label for="author">Author:</label>
        <input type="text" name="author" size="50"></input><br/>
      <label for="isbn">ISBN:</label>
        <input type="text" name="isbn" size="15"></input><br/>
      <label for="description">Description:</label><br/>
        <textarea name="description" cols="80" rows="5"></textarea><br/>
      <input type="submit"></input>
    </form>

  </body>
</html>
---------------------------------------------------------------------

. Add a simple style sheet to make our page look like a UI engineer has labored over it by placing the style sheet in  (/hello-spring-boot/src/main/resources/static/style.css).
+
[source,css]
---------------------------------------------------------------------
vvbody {
	background-color: #cccccc;
	font-family: arial,helvetica,sans-serif;
}

.bookHeadline {
	font-size: 12pt;
	font-weight: bold;
}

.bookDescription {
	font-size: 10pt;
}

label {
	font-weight: bold;
}
---------------------------------------------------------------------

Completed:  Our main only has the role of bootstrapping the application. 
+
[source,java]
---------------------------------------------------------------------
package io.pivotal;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DataJpaSpringBootApplication {

	public static void main(String[] args) {
		SpringApplication.run(DataJpaSpringBootApplication.class, args);
	}
}

---------------------------------------------------------------------

== Run the _data-jap-spring-boot_ Application

. In a terminal, change working directory to *CN-Workshop-TM/labs/lab01/data-jpa-spring-boot*
+
$ cd /CN-Workshop-TM/labs/lab02/data-jpa--spring-boot

. Run the application
+
$ mvn clean spring-boot:run

. You should see the application start up an embedded Apache Tomcat server on port 8080 (review terminal output):
+
[source,bash]
---------------------------------------------------------------------
2015-10-02 13:26:59.264  INFO 44749 --- [lication.main()] s.b.c.e.t.TomcatEmbeddedServletContainer: Tomcat started on port(s): 8080 (http)
2015-10-02 13:26:59.267  INFO 44749 --- [lication.main()] io.pivotal.hello.HelloSpringBootApplication: Started HelloSpringBootApplication in 2.541 seconds (JVM running for 9.141)
---------------------------------------------------------------------

. Browse to http://localhost:8080

. Stop the _hello-spring-boot_ application. In the terminal window: *Ctrl + C*

== Deploy _data-jpa-spring-boot_ to Pivotal Cloud Foundry

. Build the application
+
[source,bash]
---------------------------------------------------------------------
$ mvn clean package
---------------------------------------------------------------------

. Create an application manifest in the root folder /hello-spring-boot
+
$ touch manifest.yml

. Add application metadata
+
[source, bash]
---------------------------------------------------------------------
---
applications:
- name: data-jpa-spring-boot
  host: data-jpa-spring-boot-${random-word}
  memory: 512M
  instances: 1
  path: ./target/data-jpa-spring-boot-0.0.1-SNAPSHOT.jar
  buildpack: java_buildpack_offline
---------------------------------------------------------------------

. Push application into Cloud Foundry
+
$ cf push -f manifest.yml

. Find the URL created for your app in the health status report. Browse to your app.

*Congratulations!* You’ve just added persistence to a Spring Boot application.

