= Building a Spring Boot Application

== Create a Spring Boot Project

. Browse to https://start.spring.io

. Generate a Maven Project with Spring Boot 1.3 (if this version is unavailable then get the latest 1.3.X version, but no SNAPSHOTS).

. Fill out the *Project metadata* fields as follows:
+
Group:: `io.spring.pivotal`
Artifact:: `hello-spring-boot`

. In the dependencies section, add the following:
+
Web

. Click the Generate Project button. Your browser will download a zip file. Unpack that zip file.

. Import the project’s pom.xml into your editor/IDE of choice.

*STS Import Help:*

Select File > Import… Then select Maven > Existing Maven Projects. On the Import Maven Projects page, browse to the /hello-spring-boot directory (e.g. ~/repos/hello-spring-boot)

== Add and Endpoint

. Add an @RestController annotation to the class io.pivotal.HelloSpringBootApplication (/hello-spring-boot/src/main/java/io/pivotal/HelloSpringBootApplication.java).
+
[source, java]
package io.pivotal;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class HelloSpringBootApplication {

    public static void main(String[] args) {
        SpringApplication.run(HelloSpringBootApplication.class, args);
    }
}
